### PR TITLE
Speed up and minor fixes

### PR DESCRIPTION
**Pull request by pablomayobre**
### Speed Up
This pull-request tries to speed up the activation time of love-atom, which although very good it can still be faster. This is basically done by loading the dependencies in an idle callback, that is, when Atom is idle, so that it won't waste unnecessary resources at start up.

With this I also moved the loading of the JSON file to this idle callback, passing the completions through the `LoveProvider` `constructor` function. This speeds up the first time `getOptions` is called, since before it needed to find the file and parse it before actually reviving it, so now this happens when Atom is idle or at worst when the object is created.

### Linting Issue
When love-atom was moved over to an atom-autocomplete-lua it was decided that CoffeeScript would be dropped and ES6 would be used instead, and in this process a linter was chosen to keep a consistent code style and quality, this all happened in commit a4586aaaa05401956501e9a56b4400e12b7a0887 in the `package.json` file, but the JS had several linting errors so this were fixed.

### Lua Version
I suggested adding the `luaVersion` to the JSON file since LÖVE most of the time uses LuaJIT, but this was an error in my part. Autocomplete-Lua actually has an option in its configuration that allows you to change the Lua version of the `StdProvider`, which is the default provider and it has a really low priority, love-atom was overriding this configuration which I consider was not an intended behavior. The `luaVersion` can now be configured from the Autocomplete-Lua package configurations or through the `.luacompleterc` file

### CODE REVIEW

**Comment by pablomayobre** [comment]
Some other notes:
* The idle callback is named `installLoveAtomDeps` so that you can easily debug if it is being called in the inspector (since idle callback debugging can be a tricky business)
* `loadDeps` is called when `getProvider` is called, but if it had been called before in an idle callback it won't do anything, it's called there in order to make sure that when `getProvider` is called the dependencies will be loaded (since the idle callback may not have executed by then)
* If `loadDeps` is called in `getProvider` before the idle callback runs, the idle callback will call `loadDeps` again but this time it will do nothing.
* The idle callbacks are all canceled when the package deactivates, future idle callbacks could be added to the `Set`
* Even though the `completions` from the JSON are passed to the constructor, they still need to be revived the first time `getOptions` runs, this is because `utils` is only passed when `getOptions` is called.

**Comment by rm-code** [comment]
@Positive07 Thanks, looks good to me :)

Btw which linter package are you using for your JS projects?

**Comment by pablomayobre** [comment]
For this package I set up [Standard JS](https://github.com/feross/standard), which I use with [linter-js-standard](https://atom.io/packages/linter-js-standard), before linting with Atom you need to run `npm install` in the project though.

For other projects I have used [ESlint](https://eslint.org) with the [Airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) preset which is good but kinda exigent in the way you need to write your code, Standard is a little more flexible and looks better without all the trailing semi colons, so I prefer Standard (or its derivatives) over Airbnb

**Comment by pablomayobre** [comment]
Wow! We went from almost 2 seconds to 12 milliseconds! A really good improvement 😄 🎉

**Pull request merged**
